### ISSUE TITLE
How to make the game detect the controller?

### ISSUE THREAD

**Issue by asesidaa** [watiko/beatble-rs#9]
I am using an Arm SBC with a bluetooth dongle. My game is on iOS.

Currently, I paired my iPad and the SBC, but in game the controller is not detected, and the program detects no notify request. However, when using bluetooth debug programs, I can trigger notify request and get data properly. 
I wonder what is the correct way to set up?

**Comment by watiko** [comment]
@asesidaa 
(I'm assuming you're talking about a program that was implemented using my program as a reference.)
I wrote [an article about this program](https://watiko.net/2020/12/08/playing-beatmania-iidx-um-with-unofficial-controller/) in Japanese. The important parts related to this issue is the following.

```
+------------------------+
|Peripheral              |
| Name: IIDX Entry model |
| +----------------------|
| |Primary Service       |
| | UUID: 0xFF00         |
| | +--------------------|
| | |Characteristic      |
| | | UUID: 0xFF01       |
| | | Properties: notify |
+------------------------+
```

https://github.com/watiko/beatble-rs/blob/153900b67c015273f6dd45584e65b0ac59f28b81/src/main.rs#L16

https://github.com/watiko/beatble-rs/blob/153900b67c015273f6dd45584e65b0ac59f28b81/src/ble/key_input/service.rs#L9

https://github.com/watiko/beatble-rs/blob/153900b67c015273f6dd45584e65b0ac59f28b81/src/ble/key_input/characteristics.rs#L21

If these information does not match, the device will not attempt to connect.

**Comment by asesidaa** [comment]
HI, thank you for reply. I have found out that my bluetooth module has some signal issue, which makes the connection very unstable,after I changed that, it now works fine.
